"""Initial migration.

Revision ID: 37abfb16cf5a
Revises: 
Create Date: 2024-10-07 08:36:50.926124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37abfb16cf5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('produce',
    sa.Column('produce_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('produce_id')
    )
    op.create_table('processed_food',
    sa.Column('processed_food_id', sa.Integer(), nullable=False),
    sa.Column('produce_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produce_id'], ['produce.produce_id'], ),
    sa.PrimaryKeyConstraint('processed_food_id')
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('produce_id', sa.Integer(), nullable=True),
    sa.Column('processed_food_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['processed_food_id'], ['processed_food.processed_food_id'], ),
    sa.ForeignKeyConstraint(['produce_id'], ['produce.produce_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('processed_food')
    op.drop_table('produce')
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
